# Generated by Django 4.0.4 on 2022-05-22 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('color', models.CharField(max_length=40)),
                ('log', models.FileField(upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('new_created', models.DateTimeField(auto_now_add=True)),
                ('time_close', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Social_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_username', models.CharField(max_length=15)),
                ('url', models.URLField()),
                ('new_created', models.DateTimeField(auto_now_add=True)),
                ('new_update', models.DateTimeField(auto_now=True)),
                ('numbers_clicks', models.IntegerField(default=0)),
                ('social_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respond.social_options')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
