# Generated by Django 4.0.4 on 2022-05-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_profile',
            name='socialProfileUsername',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
    ]
