# Generated by Django 4.0.4 on 2022-05-26 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('respond', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_extended',
            name='user_id',
        ),
        migrations.AddField(
            model_name='users_extended',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
