# Generated by Django 4.0.2 on 2022-02-20 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='Link1',
            new_name='link1',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='Link10',
            new_name='link10',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='Link2',
            new_name='link2',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='Link3',
            new_name='link3',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='Link4',
            new_name='link4',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='Link5',
            new_name='link5',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='Link6',
            new_name='link6',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='Link7',
            new_name='link7',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='Link8',
            new_name='link8',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='Link9',
            new_name='link9',
        ),
        migrations.AlterField(
            model_name='users',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='respond.links'),
        ),
    ]
