# Generated by Django 4.0.4 on 2022-05-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0002_alter_social_profile_userurl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_extended',
            name='created_At',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='users_extended',
            name='updated_At',
            field=models.DateTimeField(editable=False),
        ),
    ]
