# Generated by Django 4.0.2 on 2022-02-20 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0002_rename_link1_links_link1_rename_link10_links_link10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respond.links'),
        ),
    ]
