# Generated by Django 4.0.4 on 2022-05-27 23:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0003_alter_users_extended_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_profile',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
