# Generated by Django 4.0.4 on 2022-05-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0003_rename_query_username_social_urls_username_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_urls',
            name='username_id',
        ),
    ]
