# Generated by Django 4.0.4 on 2022-05-26 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('respond', '0003_users_extend_delete_users_extended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_extend',
            name='job',
        ),
        migrations.AddField(
            model_name='users_extend',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='users_extend',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users_extend',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users_extend',
            name='phone',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
