# Generated by Django 4.0.2 on 2022-02-21 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0003_alter_users_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='static/images/banner.jpg', upload_to='')),
                ('img2', models.ImageField(default='static/images/banner.jpg', upload_to='')),
                ('img3', models.ImageField(default='static/images/banner.jpg', upload_to='')),
                ('img4', models.ImageField(default='static/images/banner.jpg', upload_to='')),
                ('img5', models.ImageField(default='static/images/banner.jpg', upload_to='')),
                ('img6', models.ImageField(default='static/images/banner.jpg', upload_to='')),
                ('img7', models.ImageField(default='static/images/banner.jpg', upload_to='')),
                ('img8', models.ImageField(default='static/images/banner.jpg', upload_to='')),
                ('img9', models.ImageField(default='static/images/banner.jpg', upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='links',
            name='link10',
        ),
        migrations.AddField(
            model_name='users',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respond.images'),
        ),
    ]
