# Generated by Django 4.0.4 on 2022-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0004_remove_social_urls_username_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_urls',
            name='username_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
