# Generated by Django 4.0.4 on 2022-05-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0005_alter_social_profile_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_profile',
            old_name='created_At',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='social_profile',
            old_name='updated_At',
            new_name='updated_at',
        ),
    ]
