# Generated by Django 4.0.4 on 2022-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0005_alter_social_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_extended',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='photos'),
        ),
    ]
