# Generated by Django 4.0.4 on 2022-05-22 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('respond', '0005_social_urls_username_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_urls',
            name='social_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='respond.social_options'),
        ),
        migrations.AlterField(
            model_name='social_urls',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
