# Generated by Django 4.0.4 on 2022-06-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0006_alter_users_extended_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_extended',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='photos'),
        ),
    ]
