# Generated by Django 4.0.4 on 2022-05-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0006_alter_social_urls_social_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_options',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
