# Generated by Django 4.0.4 on 2022-05-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0006_rename_created_at_social_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_profile',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='social_profile',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
