# Generated by Django 4.0.4 on 2022-05-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0007_alter_social_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_profile',
            name='created_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='social_profile',
            name='updated_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
