# Generated by Django 4.0.4 on 2022-05-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0007_alter_social_options_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_options',
            name='url',
            field=models.URLField(),
        ),
    ]
