# Generated by Django 4.0.4 on 2022-05-29 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('respond', '0008_alter_social_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_profile',
            name='userurl_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users_extended',
            name='created_At',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='users_extended',
            name='updated_At',
            field=models.DateTimeField(),
        ),
    ]
