# Generated by Django 4.0.4 on 2022-05-22 20:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('respond', '0008_alter_social_options_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_options',
            new_name='Social_option',
        ),
        migrations.RenameModel(
            old_name='Social_urls',
            new_name='Social_url',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='Users_extend',
        ),
    ]
