# Generated by Django 4.0.4 on 2022-06-14 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('respond', '0008_alter_users_extended_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_extended',
            name='phone',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.CreateModel(
            name='stats_table',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_of_times_visited', models.IntegerField(default=0)),
                ('number_of_times_shared', models.IntegerField(default=0)),
                ('number_of_times_clicked', models.IntegerField(default=0)),
                ('number_of_times_liked', models.IntegerField(default=0)),
                ('first_visit_date', models.DateTimeField(auto_now_add=True)),
                ('last_visit_date', models.DateTimeField(auto_now=True)),
                ('url_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='respond.urloption')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
