# Generated by Django 4.0.4 on 2022-06-20 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('respond', '0009_alter_users_extended_phone_stats_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_profile',
            name='urlOptionId',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='respond.urloption'),
        ),
        migrations.AlterField(
            model_name='social_profile',
            name='userurl_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users_extended',
            name='image',
            field=models.FileField(blank=True, default='photos/téléchargement.jpeg', null=True, upload_to='photos'),
        ),
    ]
