# Generated by Django 4.0.4 on 2022-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0009_rename_social_options_social_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_option',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
