# Generated by Django 4.0.4 on 2022-06-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0010_alter_social_profile_urloptionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_extended',
            name='image',
            field=models.ImageField(blank=True, default='photos/téléchargement.jpeg', null=True, upload_to='photos'),
        ),
    ]
