# Generated by Django 4.0.4 on 2022-06-22 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0011_alter_users_extended_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_profile',
            name='urlOptionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='respond.urloption'),
        ),
    ]
