# Generated by Django 4.0.4 on 2022-05-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0011_remove_social_option_url_social_option_url_web'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_option',
            old_name='color',
            new_name='colors',
        ),
        migrations.RenameField(
            model_name='social_option',
            old_name='log',
            new_name='logs',
        ),
    ]
