# Generated by Django 4.0.4 on 2022-05-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0012_rename_color_social_option_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_option',
            name='colors',
        ),
        migrations.AddField(
            model_name='social_option',
            name='color_log',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
