# Generated by Django 4.0.4 on 2022-05-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0013_remove_social_option_colors_social_option_color_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_option',
            name='logs',
        ),
        migrations.AddField(
            model_name='social_option',
            name='log_svg',
            field=models.FileField(blank=True, null=True, upload_to='logos'),
        ),
    ]
