# Generated by Django 4.0.4 on 2022-05-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0014_remove_social_option_logs_social_option_log_svg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_url',
            old_name='url',
            new_name='url_socials',
        ),
    ]
