# Generated by Django 4.0.4 on 2022-05-24 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0015_rename_url_social_url_url_socials'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_option_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponame', models.CharField(max_length=100)),
                ('url_web', models.URLField(blank=True)),
                ('color_log', models.CharField(blank=True, max_length=100, null=True)),
                ('log_svg', models.FileField(blank=True, null=True, upload_to='logos')),
                ('log_svg_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='social_url',
            old_name='new_created',
            new_name='created_At',
        ),
        migrations.RenameField(
            model_name='social_url',
            old_name='new_update',
            new_name='updated_At',
        ),
        migrations.RenameField(
            model_name='social_url',
            old_name='username_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='users_extend',
            old_name='new_created',
            new_name='created_At',
        ),
        migrations.RenameField(
            model_name='users_extend',
            old_name='time_close',
            new_name='updated_At',
        ),
        migrations.RenameField(
            model_name='users_extend',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='social_url',
            name='numbers_clicks',
        ),
        migrations.RemoveField(
            model_name='social_url',
            name='url_socials',
        ),
        migrations.AlterField(
            model_name='social_url',
            name='social_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='respond.social_option_name'),
        ),
        migrations.DeleteModel(
            name='Social_option',
        ),
    ]
