# Generated by Django 4.0.4 on 2022-05-25 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respond', '0016_social_option_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_extend',
            old_name='user_id',
            new_name='user',
        ),
    ]
