# Generated by Django 4.0.2 on 2022-02-14 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('gmail', models.CharField(max_length=44)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link1', models.CharField(max_length=150)),
                ('Link2', models.CharField(max_length=150)),
                ('Link3', models.CharField(max_length=150)),
                ('Link4', models.CharField(max_length=150)),
                ('Link5', models.CharField(max_length=150)),
                ('Link6', models.CharField(max_length=150)),
                ('Link7', models.CharField(max_length=150)),
                ('Link8', models.CharField(max_length=150)),
                ('Link9', models.CharField(max_length=150)),
                ('Link10', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_res.users')),
            ],
        ),
    ]
