# Generated by Django 4.0.2 on 2022-02-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_res', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='link1',
            field=models.CharField(default='www.google.com', max_length=150),
        ),
        migrations.AddField(
            model_name='users',
            name='link10',
            field=models.CharField(default='www.google.com', max_length=150),
        ),
        migrations.AddField(
            model_name='users',
            name='link2',
            field=models.CharField(default='www.google.com', max_length=150),
        ),
        migrations.AddField(
            model_name='users',
            name='link3',
            field=models.CharField(default='www.google.com', max_length=150),
        ),
        migrations.AddField(
            model_name='users',
            name='link4',
            field=models.CharField(default='www.google.com', max_length=150),
        ),
        migrations.AddField(
            model_name='users',
            name='link5',
            field=models.CharField(default='www.google.com', max_length=150),
        ),
        migrations.AddField(
            model_name='users',
            name='link6',
            field=models.CharField(default='www.google.com', max_length=150),
        ),
        migrations.AddField(
            model_name='users',
            name='link7',
            field=models.CharField(default='www.google.com', max_length=150),
        ),
        migrations.AddField(
            model_name='users',
            name='link8',
            field=models.CharField(default='www.google.com', max_length=150),
        ),
        migrations.AddField(
            model_name='users',
            name='link9',
            field=models.CharField(default='www.google.com', max_length=150),
        ),
        migrations.DeleteModel(
            name='links',
        ),
    ]
