# Generated by Django 4.0.2 on 2022-03-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_res', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user1.jpeg', null=True, upload_to='photos'),
        ),
    ]
