# Generated by Django 4.0.2 on 2022-02-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_res', '0002_users_link1_users_link10_users_link2_users_link3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='users',
            name='link10',
        ),
        migrations.RemoveField(
            model_name='users',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='users',
            name='link3',
        ),
        migrations.RemoveField(
            model_name='users',
            name='link4',
        ),
        migrations.RemoveField(
            model_name='users',
            name='link5',
        ),
        migrations.RemoveField(
            model_name='users',
            name='link6',
        ),
        migrations.RemoveField(
            model_name='users',
            name='link7',
        ),
        migrations.RemoveField(
            model_name='users',
            name='link8',
        ),
        migrations.RemoveField(
            model_name='users',
            name='link9',
        ),
        migrations.AddField(
            model_name='users',
            name='links',
            field=models.JSONField(default={}),
        ),
    ]
