# Generated by Django 4.0.2 on 2022-02-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_res', '0003_remove_users_link1_remove_users_link10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='links',
            field=models.JSONField(null=True),
        ),
    ]
