# Generated by Django 4.0.2 on 2022-02-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_res', '0004_alter_users_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='links',
            field=models.JSONField(default={}),
        ),
    ]
