# Generated by Django 4.0.2 on 2022-03-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_res', '0005_alter_users_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default='user1.jpeg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='users',
            name='links',
            field=models.JSONField(null=True),
        ),
    ]
